name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
    - main


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.0"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -o app

    - name: Create ZIP package
      run: cd app && zip -r ../app.zip .

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_key: ${{ secretsAWS_SECRET_ACCESS_KEY }}
         application_name: KrypteringApi
         environment_name: KrypteringApi-env
         version_label: ${{ github.run_id }}
         region: eu-north-1
         deployment_package: app.zip
    